resources:
- repo: self

queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - npm

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  major: 2
  minor: 2

name: $(major).$(minor)$(rev:.r)

trigger:
- master

steps:
- task: VSBuild@1
  displayName: 'Build solution WorkItemMigrator'
  inputs:
    solution: src/WorkItemMigrator/WorkItemMigrator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy JiraExport files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\WorkItemMigrator\JiraExport\bin\$(BuildConfiguration)'
    Contents: |
        ApplicationInsights.config     
        Atlassian.Jira.dll
        jira-export.exe
        jira-export.exe.config
        Microsoft.AI.Agent.Intercept.dll
        Microsoft.AI.DependencyCollector.dll
        Microsoft.ApplicationInsights.dll
        Microsoft.Extensions.CommandLineUtils.dll
        Migration.Common.dll
        Migration.Common.Log.dll
        Migration.WIContract.dll
        Newtonsoft.Json.dll
        RestSharp.dll
        Semver.dll
        System.Diagnostics.DiagnosticSource.dll
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy WorkItemImport files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\WorkItemMigrator\WorkItemImport\bin\$(BuildConfiguration)'
    Contents: |
        Microsoft.TeamFoundation.Client.dll
        Microsoft.TeamFoundation.Common.dll
        Microsoft.TeamFoundation.Core.WebApi.dll
        Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll
        Microsoft.TeamFoundation.WorkItemTracking.Client.dll
        Microsoft.TeamFoundation.WorkItemTracking.Common.dll
        Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
        Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll
        Microsoft.VisualStudio.Services.Common.dll
        Microsoft.VisualStudio.Services.WebApi.dll
        Microsoft.WITDataStore32.dll
        System.Net.Http.Formatting.dll
        wi-import.exe
        wi-import.exe.config
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy sample files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\docs\samples'
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator\Samples'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: WorkItemMigrator'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    ArtifactName: WorkItemMigrator

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: WorkItemMigratorExtension'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\jira-devops-workitem-migrator-$(Build.BuildNumber).vsix'
    ArtifactName: WorkItemMigratorExtension
